# SPDX-FileCopyrightText: Andrei Gherzan <andrei@gherzan.com>
#
# SPDX-License-Identifier: MIT

run:
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - gocyclo
    - gofmt
    - govet
    - ineffassign
    - misspell
